
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author jefmelo
 */
public class Mainly extends javax.swing.JFrame {

    /**
     * Creates new form Mainly
     */
    public Connection conn = null;
    public Statement stmt;
    public ResultSet rs;

    public Mainly() {
        initComponents();

        abas.setEnabledAt(1, false);
    }

    public Statement abre_conexao() {

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/DbAplication",
                    "root", "123");

            stmt = conn.createStatement(
                    ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE
            );

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }

        return stmt;

    }

    public void limpa_campos() {
        txtSigla.setText("");
        txtNome.setText("");
        txtAreaDesc.setText("");
    }

    public void atualiza_campos() {
        try {
            txtSigla.setText(rs.getString("Sigla"));
            txtNome.setText(rs.getString("Nome"));
            txtAreaDesc.setText(rs.getString("Descricao"));
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    public void abreTabela() throws SQLException {
        String sql = "Select * from curso";

        stmt = abre_conexao();

        rs = stmt.executeQuery(sql);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abas = new javax.swing.JTabbedPane();
        abaLogin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        abaConectado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSigla = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDesc = new javax.swing.JTextArea();
        btnInserir = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnPrimeiro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        abaLogin.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        btnLogin.setText("Conectar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(369, 220, 90, 28);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Senha");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 100, 480, 20);

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(10, 50, 460, 28);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usuário");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 26, 460, 20);
        jPanel1.add(txtSenha);
        txtSenha.setBounds(10, 120, 460, 28);

        abaLogin.add(jPanel1);
        jPanel1.setBounds(50, 40, 480, 260);

        abas.addTab("Login", abaLogin);

        abaConectado.setLayout(null);

        jLabel3.setText("Sigla");
        abaConectado.add(jLabel3);
        jLabel3.setBounds(20, 30, 28, 16);
        abaConectado.add(txtSigla);
        txtSigla.setBounds(20, 50, 428, 28);

        jLabel4.setText("Nome");
        abaConectado.add(jLabel4);
        jLabel4.setBounds(20, 100, 34, 16);
        abaConectado.add(txtNome);
        txtNome.setBounds(20, 120, 428, 28);

        txtAreaDesc.setColumns(20);
        txtAreaDesc.setRows(5);
        jScrollPane1.setViewportView(txtAreaDesc);

        abaConectado.add(jScrollPane1);
        jScrollPane1.setBounds(20, 170, 428, 155);

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        abaConectado.add(btnInserir);
        btnInserir.setBounds(20, 330, 63, 28);

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        abaConectado.add(btnDeletar);
        btnDeletar.setBounds(190, 330, 83, 28);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        abaConectado.add(btnAtualizar);
        btnAtualizar.setBounds(370, 330, 74, 28);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        abaConectado.add(btnLimpar);
        btnLimpar.setBounds(520, 330, 67, 28);

        btnAnterior.setText("< Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        abaConectado.add(btnAnterior);
        btnAnterior.setBounds(180, 420, 100, 28);

        btnProximo.setText("Próximo >");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });
        abaConectado.add(btnProximo);
        btnProximo.setBounds(360, 420, 100, 28);

        btnUltimo.setText("Último >>");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        abaConectado.add(btnUltimo);
        btnUltimo.setBounds(500, 420, 90, 28);

        btnPrimeiro.setText("<< Primeiro");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });
        abaConectado.add(btnPrimeiro);
        btnPrimeiro.setBounds(10, 420, 100, 28);

        abas.addTab("Conectado", abaConectado);

        getContentPane().add(abas);
        abas.setBounds(0, 20, 600, 490);

        setBounds(0, 0, 621, 547);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        String senha = new String(txtSenha.getPassword());

        if (txtUsuario.getText().equals("adm") && senha.equals("123")) {
            abas.setEnabledAt(1, true);
            abas.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "Usuário ou Senha Não Conferem",
                    "Mensagem",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
        try {

            String sql = String.format(
                    "INSERT INTO curso VALUES('%s', '%s', '%s')",
                    txtSigla.getText(),
                    txtNome.getText(),
                    txtAreaDesc.getText());

            JOptionPane.showMessageDialog(null, sql);

            stmt = abre_conexao();

            int i;
            i = stmt.executeUpdate(sql);//executando o comando sql
            stmt.close();

            if (i > 0) {
                JOptionPane.showMessageDialog(null, "Curso cadastrado com sucesso!");
                abreTabela();
            }
        } catch (SQLException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
        try {
            stmt = abre_conexao();

            String sql = String.format("DELETE FROM curso WHERE(sigla='%s')", txtSigla.getText());

            JOptionPane.showMessageDialog(null, sql);

            int i;
            i = stmt.executeUpdate(sql);
            stmt.close();

            if (i > 0) {
                JOptionPane.showMessageDialog(null, "Curso deletado com sucesso!");
                limpa_campos();
                abreTabela();
            }
        } catch (SQLException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        try {
            stmt = abre_conexao();

            String sql = String.format(
                    "UPDATE curso SET sigla='%s', nome='%s', descricao='%s' where sigla='%s'",
                    txtSigla.getText(),
                    txtNome.getText(),
                    txtAreaDesc.getText(),
                    txtSigla.getText());

            JOptionPane.showMessageDialog(null, sql);
            int i;
            i = stmt.executeUpdate(sql);//executando o comando sql
            int y;
            stmt.close();
            y = Statement.CLOSE_CURRENT_RESULT;
            if (i > 0 || y > 0) {
                JOptionPane.showMessageDialog(null, "Curso alterado com sucesso!");
                abreTabela();
            } else if (i > 0) {
                stmt.close();
            }
        } catch (SQLException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        limpa_campos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        // TODO add your handling code here:
        try {
            rs.first();
            atualiza_campos();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        try {
            rs.previous();
            atualiza_campos();
        } catch (SQLException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        // TODO add your handling code here:
        try {
            rs.next();
            atualiza_campos();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        // TODO add your handling code here:
        try {
            rs.last();
            atualiza_campos();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            abreTabela();
        } catch (SQLException ex) {
            Logger.getLogger(Mainly.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Mainly().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaConectado;
    private javax.swing.JPanel abaLogin;
    private javax.swing.JTabbedPane abas;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaDesc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtSigla;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
